LAB10/back/api/urls.py
from django.urls import path

from rest_framework_simplejwt.views import TokenObtainPairView

from . import views

app_name = 'api'
urlpatterns = [
    path('', views.index, name='index'),
    path('companies', views.all_companies, name='all_companies'),
    path('companies/<int:id>/', views.a_company, name='a_company'),
    path('companies/<int:id>/vacancies/', views.get_vacancies, name='get_vacancies'),
    path('vacancies/', views.VacanciesView.as_view(), name='all_vacancies'),
    path('vacancies/<int:id>/', views.A_VacancyView.as_view(), name='a_vacancy'),
    path('vacancies/top_ten/', views.top_ten, name='top_ten'),
    path('login/', TokenObtainPairView.as_view()),
]

LAB10/back/hh_back/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

LAB10/back/api/models.py
from django.db import models

# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    city = models.CharField(max_length=100, default="None")
    address = models.TextField()

    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Companies"

    def __str__(self):
        return self.name

    def to_json(self):
        return {
            'id': self.id,
            'name': self.name,
            'description': self.description,
            'city': self.city,
            'address': self.address
        }

class Vacancy(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    salary = models.FloatField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='vacancies')

    class Meta:
        verbose_name = "Vacancy"
        verbose_name_plural = "Vacancies"

    def __str__(self):
        return self.name

    def to_json(self):
        return {
            'id': self.id,
            'name': self.name,
            'description': self.description,
            'salary': self.salary,
            'company': str(self.company)
        }

LAB10/back/api/views/views_1.py

from django.views.generic import View
from django.shortcuts import render

from rest_framework.decorators import api_view, APIView, permission_classes
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated

from ..models import Company, Vacancy
from ..serializers import CompanySerializer, VacancySerializer

# Create your views here.

def index(request):
    return render(request, 'api/index.html', locals())

@api_view(['GET', 'POST'])
#@permission_classes([IsAuthenticated])
def all_companies(request):
    #permission_classes = ([IsAuthenticated])

    if request.method == "GET":
        try:
            comp = Company.objects.all()
            serializer = CompanySerializer(comp, many=True)
        except Exception as e:
            return Response({'message': str(e)}, status=404)
        return Response(serializer.data)

    elif request.method == "POST":
        serializer = CompanySerializer(data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors)

@api_view(['GET', 'PUT', 'DELETE'])
#@permission_classes([IsAuthenticated])
def a_company(request, id):
    try:
        comp = Company.objects.get(id=id)
    except Company.DoesNotExist as e:
        return Response({'message': str(e)}, status=400)

    if request.method == "GET":
        serializer = CompanySerializer(comp)
        return Response(serializer.data)
    elif request.method == "PUT":
        serializer = CompanySerializer(instance=comp, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors)
    elif request.method == "DELETE":
        comp.delete()



class VacanciesView(APIView):
    model = Vacancy
    #permission_classes = [IsAuthenticated]

    def get(self, request):
        try:
            vac = Vacancy.objects.all()
            serializer = VacancySerializer(vac, many=True)
        except Exception as e:
            return Response({'message': str(e)}, status=404)
        return Response(serializer.data)

    def post(self, request):
        serializer = VacancySerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors)


class A_VacancyView(APIView):
    model = Vacancy
    #permission_classes = [IsAuthenticated]

    def get(self, request, id):
        vac = Vacancy.objects.get(id=id)
        serializer = VacancySerializer(vac)
        return Response(serializer.data)

    def put(self, request, id):
        vac = Vacancy.objects.get(id=id)
        serializer = VacancySerializer(instance=vac, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors)

    def delete(self, request, id):
        vac = Vacancy.objects.get(id=id)
        vac.delete()



@api_view()
def get_vacancies(request, id):
    comp = Company.objects.get(id=id)
    vac = comp.vacancies.all() #vac = comp.vacancy_set.all()
    serializer = VacancySerializer(vac, many=True)
    return Response(serializer.data)

@api_view()
def top_ten(request):
    vac = Vacancy.objects.order_by('-salary')
    serializer = VacancySerializer(vac, many=True)
    return Response(serializer.data)





















@api_view()
def range(request, min, max):
    vac = Vacancy.objects.filter(salary__gte=min).filter(salary__lte=max)
    serializer = VacancySerializer(vac, many=True)
    return Response(serializer.data)


LAB10/back/api/templates/api/a_company.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if company %}
        <h1>{{ company.name }}</h1>
        <p>{{ company.description }}</p>
        <h2>{{ company.city }}</h2>
        <h3>{{ company.address }}</h3>

        <a href="{% url 'api:get_vacancies' company.id %}">See available vacancies</a>
    {% else %}
        <p>Nothing is available.</p>
    {% endif %}
</body>
</html>

LAB10/back/api/templates/api/a_vacancy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if vacancy %}
        <h1>{{ vacancy.name }}</h1>
        <p>{{ vacancy.description }}</p>
        <h2>{{ vacancy.salary }}</h2>

    {% else %}
        <p>Nothing is available.</p>
    {% endif %}
</body>
</html>

LAB10/back/api/templates/api/companies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% if list %}
        <ul>
        {% for l in list %}
            <li><a href="{% url 'api:a_company' l.id %}">{{ l.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Nothing is available.</p>
    {% endif %}

</body>
</html>

LAB10/back/api/templates/api/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p><a href="{% url 'api:all_companies' %}">All Companies</a></p>
    <p><a href="{% url 'api:all_vacancies' %}">All Vacancies</a></p>
</body>
</html>

LAB10/back/api/templates/api/vacancies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if vacancies %}
        <a href="{%url 'api:top_ten' %}">See Top Vacancies</a>
        <ul>
        {% for v in vacancies %}
            <li><a href="{%url 'api:a_vacancy' v.id %}">{{ v.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Nothing is available.</p>
    {% endif %}
</body>
</html>